List<String> questions = [
  'Do you enjoy working with data?',
  'Are you good at managing projects and deadlines?',
  'Do you have strong programming skills?',
  'Are you creative and have an eye for design?',
  'Do you enjoy creating and managing digital marketing campaigns?',
  'Are you comfortable analyzing financial data and making forecasts?',
  'Do you have strong writing skills and enjoy crafting content?',
  'Are you good at handling HR-related tasks and employee management?',
  'Do you excel at building relationships and closing deals?',
  // Additional questions covering various fields
  'Do you enjoy helping people and have a strong desire to improve their health?',
  'Are you interested in understanding and treating mental health conditions?',
  'Do you have a passion for caring for animals and their well-being?',
  'Are you skilled at visual communication and creating aesthetically pleasing designs?',
  'Do you enjoy expressing yourself through music, performance, or other creative outlets?',
  'Are you passionate about preserving and promoting cultural heritage?',
  'Do you have a knack for cooking and experimenting with flavors?',
  'Are you patient and have a passion for educating others?',
  'Do you enjoy solving complex problems and designing innovative solutions?',
];
